# Autogenerated wrapper script for opencv_jll for x86_64-linux-gnu
export OpenCV_jl, libopencv_calib3d, libopencv_core, libopencv_dnn, libopencv_features2d, libopencv_flann, libopencv_highgui, libopencv_imgcodecs, libopencv_imgproc, libopencv_julia, libopencv_objdetect, libopencv_videoio

using Qt_jll
using Libglvnd_jll
using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("opencv")
JLLWrappers.@declare_file_product(OpenCV_jl)
JLLWrappers.@declare_library_product(libopencv_calib3d, "libopencv_calib3d.so.4.5")
JLLWrappers.@declare_library_product(libopencv_core, "libopencv_core.so.4.5")
JLLWrappers.@declare_library_product(libopencv_dnn, "libopencv_dnn.so.4.5")
JLLWrappers.@declare_library_product(libopencv_features2d, "libopencv_features2d.so.4.5")
JLLWrappers.@declare_library_product(libopencv_flann, "libopencv_flann.so.4.5")
JLLWrappers.@declare_library_product(libopencv_highgui, "libopencv_highgui.so.4.5")
JLLWrappers.@declare_library_product(libopencv_imgcodecs, "libopencv_imgcodecs.so.4.5")
JLLWrappers.@declare_library_product(libopencv_imgproc, "libopencv_imgproc.so.4.5")
JLLWrappers.@declare_library_product(libopencv_julia, "libopencv_julia.so")
JLLWrappers.@declare_library_product(libopencv_objdetect, "libopencv_objdetect.so.4.5")
JLLWrappers.@declare_library_product(libopencv_videoio, "libopencv_videoio.so.4.5")
function __init__()
    JLLWrappers.@generate_init_header(Qt_jll, Libglvnd_jll, libcxxwrap_julia_jll)
    JLLWrappers.@init_file_product(
        OpenCV_jl,
        "OpenCV.jl.tar",
    )

    JLLWrappers.@init_library_product(
        libopencv_calib3d,
        "lib/libopencv_calib3d.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_core,
        "lib/libopencv_core.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_dnn,
        "lib/libopencv_dnn.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_features2d,
        "lib/libopencv_features2d.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_flann,
        "lib/libopencv_flann.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_highgui,
        "lib/libopencv_highgui.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_imgcodecs,
        "lib/libopencv_imgcodecs.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_imgproc,
        "lib/libopencv_imgproc.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_julia,
        "lib/libopencv_julia.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_objdetect,
        "lib/libopencv_objdetect.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libopencv_videoio,
        "lib/libopencv_videoio.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
